/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package numberguess;

import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import static java.lang.System.exit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
/**
 *
 * @author Itsme
 */
public class NumGamehome extends javax.swing.JFrame {

    /**
     * Creates new form NumGamehome
     */
    public NumGamehome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Loading = new javax.swing.JLabel();
        Loadvalue = new javax.swing.JLabel();
        pbar = new javax.swing.JProgressBar();
        header = new javax.swing.JLabel();
        loader1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1700, 820));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Loading.setFont(new java.awt.Font("Imprint MT Shadow", 3, 24)); // NOI18N
        Loading.setForeground(new java.awt.Color(255, 153, 0));
        Loading.setText("Loading...");
        getContentPane().add(Loading, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 720, 610, 60));

        Loadvalue.setBackground(new java.awt.Color(255, 255, 255));
        Loadvalue.setFont(new java.awt.Font("Imprint MT Shadow", 2, 24)); // NOI18N
        Loadvalue.setForeground(new java.awt.Color(255, 255, 0));
        Loadvalue.setText("0%");
        Loadvalue.setMaximumSize(new java.awt.Dimension(29, 21));
        Loadvalue.setMinimumSize(new java.awt.Dimension(29, 21));
        Loadvalue.setPreferredSize(new java.awt.Dimension(29, 21));
        getContentPane().add(Loadvalue, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 730, 80, 55));

        pbar.setBackground(new java.awt.Color(255, 0, 0));
        pbar.setForeground(new java.awt.Color(204, 0, 204));
        getContentPane().add(pbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 784, 1540, 30));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setFont(new java.awt.Font("Imprint MT Shadow", 3, 48)); // NOI18N
        header.setForeground(new java.awt.Color(255, 255, 255));
        header.setText("NUMBER");
        header.setMaximumSize(new java.awt.Dimension(446, 55));
        header.setMinimumSize(new java.awt.Dimension(446, 55));
        header.setPreferredSize(new java.awt.Dimension(446, 55));
        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 250, 55));

        loader1.setBackground(new java.awt.Color(255, 255, 255));
        loader1.setFont(new java.awt.Font("Imprint MT Shadow", 1, 48)); // NOI18N
        loader1.setForeground(new java.awt.Color(255, 255, 255));
        loader1.setText("GUESSING GAME...!!!");
        loader1.setToolTipText("");
        loader1.setMaximumSize(new java.awt.Dimension(686, 55));
        loader1.setMinimumSize(new java.awt.Dimension(686, 55));
        loader1.setPreferredSize(new java.awt.Dimension(686, 55));
        getContentPane().add(loader1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 540, 55));

        jLabel1.setFont(new java.awt.Font("Imprint MT Shadow", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/numberguess/13 (1).jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(686, 55));
        jLabel1.setMinimumSize(new java.awt.Dimension(686, 55));
        jLabel1.setPreferredSize(new java.awt.Dimension(686, 55));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, -10, 1700, 820));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    @SuppressWarnings("empty-statement")
    public static void main(String args[]) throws InstantiationException, UnsupportedLookAndFeelException {
        try{
            for(javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
              if("Nimbus".equals(info.getName()))
              {
                  try {
                      javax.swing.UIManager.setLookAndFeel(info.getClassName());
                  } catch (IllegalAccessException ex) {
                      java.util.logging.Logger.getLogger(NumGamehome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                  }
                  break;
              }
            }
        }
        catch (ClassNotFoundException ex)
        {
          java.util.logging.Logger.getLogger(NumGamehome.class.getName()).log(java.util.logging.Level.SEVERE, null,ex);
        }
        NumGamehome ngh=new NumGamehome();
        ngh.setVisible(true);

        try{
        for(int i=0;i<=100;i++)
        {
         Thread.sleep(50);
         ngh.Loadvalue.setText(i +"%");
        if(i==10)
        { ngh.Loading.setText("Turning on Game Launcher...");
        }
        if(i==30)
        { ngh.Loading.setText("Loading Game Modules...");
        }
        if(i==50)
        { ngh.Loading.setText("Setting up Connections...");
        }
        if(i==70)
        { ngh.Loading.setText("Connections successful...");
        }
        if(i==90)
        { ngh.Loading.setText("Launching Game Application...");
        }
        ngh.pbar.setValue(i);

        }
        NumGame ng1=new NumGame();
        ng1.setVisible(true);
        }
        catch(Exception e)
        { JOptionPane.showMessageDialog(null,e);
        }     
            }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Loading;
    private javax.swing.JLabel Loadvalue;
    private javax.swing.JLabel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel loader1;
    private javax.swing.JProgressBar pbar;
    // End of variables declaration//GEN-END:variables
}
