/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package numberguess;

import static java.lang.System.exit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author Itsme
 */
public class NumGame extends javax.swing.JFrame {

    String str2="";
    private int compno=0;
    
    public NumGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        result = new javax.swing.JLabel();
        yourchoice = new javax.swing.JTextField();
        randnumdisp = new javax.swing.JLabel();
        Player = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Scoreval = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Players = new javax.swing.JTextField();
        Scorebox = new javax.swing.JLabel();
        Finish = new javax.swing.JButton();
        winlose = new javax.swing.JLabel();
        Replay = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        GU = new javax.swing.JLabel();
        Attemptsleft = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1650, 1070));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel1.setText("LET'S PLAY......!!");
        jLabel1.setMaximumSize(new java.awt.Dimension(607, 41));
        jLabel1.setMinimumSize(new java.awt.Dimension(607, 41));
        jLabel1.setPreferredSize(new java.awt.Dimension(607, 41));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 390, 60));

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Algerian", 3, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/numberguess/play.png"))); // NOI18N
        jButton1.setText("Let's Start...!");
        jButton1.setMaximumSize(new java.awt.Dimension(81, 23));
        jButton1.setMinimumSize(new java.awt.Dimension(81, 23));
        jButton1.setPreferredSize(new java.awt.Dimension(81, 23));
        jButton1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jButton1ComponentHidden(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 740, 200, 50));

        result.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        result.setForeground(new java.awt.Color(204, 0, 204));
        result.setText("   ---Status---");
        result.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        result.setMaximumSize(new java.awt.Dimension(136, 36));
        result.setMinimumSize(new java.awt.Dimension(136, 36));
        result.setPreferredSize(new java.awt.Dimension(136, 36));
        result.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resultMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                resultMouseEntered(evt);
            }
        });
        getContentPane().add(result, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 500, 330, 50));

        yourchoice.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        yourchoice.setForeground(new java.awt.Color(255, 0, 51));
        yourchoice.setMinimumSize(new java.awt.Dimension(64, 36));
        yourchoice.setPreferredSize(new java.awt.Dimension(64, 36));
        getContentPane().add(yourchoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, 170, 40));

        randnumdisp.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        randnumdisp.setForeground(new java.awt.Color(255, 0, 51));
        randnumdisp.setText("    ");
        randnumdisp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        randnumdisp.setMaximumSize(new java.awt.Dimension(159, 36));
        randnumdisp.setMinimumSize(new java.awt.Dimension(159, 36));
        randnumdisp.setPreferredSize(new java.awt.Dimension(159, 36));
        randnumdisp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                randnumdispMouseClicked(evt);
            }
        });
        getContentPane().add(randnumdisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 580, 210, 50));

        Player.setBackground(new java.awt.Color(255, 255, 255));
        Player.setFont(new java.awt.Font("Georgia", 2, 24)); // NOI18N
        Player.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Player, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 90, 130));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Imprint MT Shadow", 3, 24)); // NOI18N
        jLabel2.setText("GUESSING STATUS");
        jLabel2.setMaximumSize(new java.awt.Dimension(151, 21));
        jLabel2.setMinimumSize(new java.awt.Dimension(151, 21));
        jLabel2.setPreferredSize(new java.awt.Dimension(151, 21));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 388, 70));

        Scoreval.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        Scoreval.setText("SCORE");
        Scoreval.setMaximumSize(new java.awt.Dimension(68, 21));
        Scoreval.setMinimumSize(new java.awt.Dimension(68, 21));
        Scoreval.setPreferredSize(new java.awt.Dimension(68, 21));
        getContentPane().add(Scoreval, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 580, 150, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Imprint MT Shadow", 3, 24)); // NOI18N
        jLabel3.setText("GENERATED RANDOM NUMBER");
        jLabel3.setToolTipText("");
        jLabel3.setMaximumSize(new java.awt.Dimension(321, 21));
        jLabel3.setMinimumSize(new java.awt.Dimension(321, 21));
        jLabel3.setPreferredSize(new java.awt.Dimension(321, 21));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 430, 55));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Imprint MT Shadow", 3, 24)); // NOI18N
        jLabel4.setText("ENTERED CHOICE ");
        jLabel4.setMaximumSize(new java.awt.Dimension(270, 21));
        jLabel4.setMinimumSize(new java.awt.Dimension(270, 21));
        jLabel4.setPreferredSize(new java.awt.Dimension(270, 21));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 388, 55));

        Players.setFont(new java.awt.Font("Century Schoolbook", 0, 24)); // NOI18N
        Players.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayersActionPerformed(evt);
            }
        });
        getContentPane().add(Players, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 190, 40));

        Scorebox.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        Scorebox.setForeground(new java.awt.Color(255, 0, 0));
        Scorebox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        Scorebox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ScoreboxMouseClicked(evt);
            }
        });
        getContentPane().add(Scorebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 560, 120, 60));

        Finish.setBackground(new java.awt.Color(255, 0, 51));
        Finish.setFont(new java.awt.Font("Algerian", 3, 18)); // NOI18N
        Finish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/numberguess/logout.png"))); // NOI18N
        Finish.setText("CLOSE");
        Finish.setMaximumSize(new java.awt.Dimension(82, 23));
        Finish.setMinimumSize(new java.awt.Dimension(82, 23));
        Finish.setPreferredSize(new java.awt.Dimension(82, 23));
        Finish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FinishMouseClicked(evt);
            }
        });
        getContentPane().add(Finish, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 20, 130, 50));

        winlose.setFont(new java.awt.Font("Century Schoolbook", 3, 24)); // NOI18N
        winlose.setForeground(new java.awt.Color(255, 0, 51));
        winlose.setIcon(new javax.swing.ImageIcon("C:\\Users\\Itsme\\OneDrive\\Desktop\\images.png")); // NOI18N
        winlose.setText(" WIN/LOSE");
        winlose.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        winlose.setMaximumSize(new java.awt.Dimension(192, 36));
        winlose.setMinimumSize(new java.awt.Dimension(192, 36));
        winlose.setPreferredSize(new java.awt.Dimension(192, 36));
        winlose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                winloseMouseClicked(evt);
            }
        });
        getContentPane().add(winlose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 680, 310, 90));

        Replay.setBackground(new java.awt.Color(255, 153, 255));
        Replay.setFont(new java.awt.Font("Algerian", 3, 18)); // NOI18N
        Replay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/numberguess/replay.png"))); // NOI18N
        Replay.setText("REPLAY");
        Replay.setMaximumSize(new java.awt.Dimension(82, 23));
        Replay.setMinimumSize(new java.awt.Dimension(82, 23));
        Replay.setPreferredSize(new java.awt.Dimension(82, 23));
        Replay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReplayMouseClicked(evt);
            }
        });
        getContentPane().add(Replay, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 740, 140, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/numberguess/video (4).jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 100, 450, 310));

        GU.setFont(new java.awt.Font("Imprint MT Shadow", 3, 24)); // NOI18N
        GU.setText("ATTEMPTS LEFT ->>");
        GU.setMaximumSize(new java.awt.Dimension(110, 21));
        GU.setMinimumSize(new java.awt.Dimension(110, 21));
        GU.setPreferredSize(new java.awt.Dimension(110, 21));
        getContentPane().add(GU, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 500, 320, -1));

        Attemptsleft.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        Attemptsleft.setForeground(new java.awt.Color(255, 0, 51));
        Attemptsleft.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        Attemptsleft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AttemptsleftMouseClicked(evt);
            }
        });
        getContentPane().add(Attemptsleft, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 470, 120, 60));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 102));
        jLabel6.setText("PLAYER'S NAME");
        jLabel6.setMaximumSize(new java.awt.Dimension(147, 21));
        jLabel6.setMinimumSize(new java.awt.Dimension(147, 21));
        jLabel6.setPreferredSize(new java.awt.Dimension(147, 21));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 388, 55));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/numberguess/yellow.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1540, 920));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_resultMouseClicked

    private void randnumdispMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_randnumdispMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_randnumdispMouseClicked

    private void AttemptsleftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AttemptsleftMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AttemptsleftMouseClicked

    private void ScoreboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScoreboxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ScoreboxMouseClicked

    private void PlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlayersActionPerformed

    private void winloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_winloseMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_winloseMouseClicked

    private void jButton1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jButton1ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ComponentHidden

    private void ReplayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReplayMouseClicked
      yourchoice.setText("");
      result.setText("");
      winlose.setText("");
      randnumdisp.setText("");
      Attemptsleft.setText("3");
      GU.setText("ATTEMPTS AVAILABLE");
      Scorebox.setText("");
    }//GEN-LAST:event_ReplayMouseClicked

    private void FinishMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FinishMouseClicked
        String url = "jdbc:mysql://localhost:3306/guessnum";
        String username = "root";
        String password = "";
        String playname = Players.getText();
        String win_lose = winlose.getText();
       
        // SQL query for insertion
        String insertQuery = "INSERT INTO player (playname, winlose) VALUES (?, ?)";

        // Establish a database connection
        try (Connection connection = DriverManager.getConnection(url, username, password);
             java.sql.PreparedStatement preparedStatement = connection.prepareStatement(insertQuery))
        {

            // Set parameters for the prepared statement
            preparedStatement.setString(1, playname);
            preparedStatement.setString(2, win_lose);

            // Execute the insertion
            int rowsAffected = preparedStatement.executeUpdate();
            if (rowsAffected > 0) 
            {
                System.out.println("DATA INSERTION SUCCESSFUL!!");
            }
            else 
            {
                System.out.println("SORRY, FAILED TO INSERT DATA..!!");
            }

        } 
        catch (SQLException e) {
            System.err.println("OOPS, ERROR IN EITHER CONNECTION/INSERTION: " + e.getMessage());
            e.printStackTrace();
        }
        
        exit(0);
    }//GEN-LAST:event_FinishMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(Players.getText().isEmpty() )
    {
       JOptionPane.showMessageDialog(null,"DOESN'T KNOW WHO'S GONNA PLAY..?\nSO PROVIDE A PLAYER NAME TO CONTINUE...!!!");
        
     }
    else{
    {
    for(int i=3;i>=1;i--){
        
         String a=JOptionPane.showInputDialog(this,"Enter number between 1-100");
         int guess =(i-1);
         GU.setText("ATTEMPTS LEFT ->");
         Attemptsleft.setText(Integer.toString(guess));
         yourchoice.setText(a);
       
         //to generate random number
         compno = (int)( Math.random()*100+1);
         str2 = Integer.toString(compno);
         randnumdisp.setText(str2);  
           
        String user =yourchoice.getText();
        int un=Integer.parseInt(user);

        if(un <=0 || un> 100)
        {
        result.setText("INVALID!");
        JOptionPane.showMessageDialog(null,"OOPS!!...INVALID GUESS");
   
        }
        else if (un==compno)
        {   
            result.setText("HURRAY, ITS A VALID GUESS!!");
            if(guess==2)
            {    
                 Scorebox.setText("100");
                 JOptionPane.showMessageDialog(null," VALID GUESS !!---GUESSED AT 1st  ATTEMPT ");    
            }
            else if(guess==1)
            {
                  JOptionPane.showMessageDialog(null," VALID GUESS !!---GUESSED AT 2nd  ATTEMPT ");
                  Scorebox.setText("75");
            }
            else if (guess==0)
            {
                  JOptionPane.showMessageDialog(null," VALID GUESS !!---GUESSED AT 3rd  ATTEMPT ");
                 Scorebox.setText("50");
            }
        winlose.setText("!!..WON..!!");
        JOptionPane.showMessageDialog(null," YEA!, YOU WON !");
        break;
 
  
        }
        else if  (un>compno)
        {
         result.setText(" HIGH!");
         JOptionPane.showMessageDialog(null," HIGH GUESS");
        }
        else if (un<compno)
        { 
             result.setText("LOW!");
          JOptionPane.showMessageDialog(null," LOW GUESS");
        }
        if(guess ==0 )
    {
    Scorebox.setText("--");
    winlose.setText("!!--LOST--!!");}
     
    }}}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void resultMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_resultMouseEntered

private void replayMouseClicked(java.awt.event.MouseEvent evt) {                                    
     // playerf.setText("");
      
}

                                       

    /**
     * @param args the command line arguments
     */
@SuppressWarnings("empty-statement")
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NumGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NumGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NumGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NumGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NumGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Attemptsleft;
    private javax.swing.JButton Finish;
    private javax.swing.JLabel GU;
    private javax.swing.JLabel Player;
    private javax.swing.JTextField Players;
    private javax.swing.JButton Replay;
    private javax.swing.JLabel Scorebox;
    private javax.swing.JLabel Scoreval;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel randnumdisp;
    private javax.swing.JLabel result;
    private javax.swing.JLabel winlose;
    private javax.swing.JTextField yourchoice;
    // End of variables declaration//GEN-END:variables
static class load {

        public load() {
        }
    }

}
